version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: anthony/kafka4postgres
#    container_name: kafka
    build: .
    ports:
      - "9092:9092"
#      - "9092"
#    expose:
#      - "19092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 65.108.60.87
#      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
#      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
#      HOSTNAME_COMMAND: "ip a | grep inet | grep -v 127 | awk '{print $$2}' | awk -F/ '{print $$1}'"
#      PORT_COMMAND: "CONTAINER=$$(docker ps | grep 9092 | awk '{print $$1}'); docker port $$CONTAINER 9092 | sed -e \"s/0.0.0.0://g\" | tr -d \"\n\" | cut -d: -f1"
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_PORT: 2181
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
      KAFKA_CREATE_TOPICS_SEPARATOR: ","
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#      KAFKA_LISTENERS: LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,LISTENER_DOCKER_INTERNAL://kafka:19092
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL

      ### Configuration for Single Broker Kafka
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://0.0.0.0:9092,INTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:19092,EXTERNAL_SAME_HOST://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:19092,EXTERNAL_SAME_HOST://${KAFKA_ADVERTISED_HOST_NAME}:9092
#      KAFKA_ADVERTISED_LISTENERS: EXTERNAL_SAME_HOST://localhost:_{PORT_COMMAND},INTERNAL://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:19092"
    depends_on:
      - kafka
